In [2]:
import pandas as pd

In [3]:
# Mostrar todas as colunas
pd.set_option('display.max_columns', None)

# Mostrar todas as linhas
pd.set_option('display.max_rows', None)

# Mostrar todo o conteúdo das células (sem "...")
pd.set_option('display.max_colwidth', None)

# Evita quebra de linha automática
pd.set_option('display.expand_frame_repr', False)

In [4]:
df_c = pd.read_csv("../../../dados/dados_siape_bruto/descompactado/202411_Servidores_SIAPE/202411_Cadastro.csv", encoding='iso-8859-1', sep=";")
df_r = pd.read_csv("../../../dados/dados_siape_bruto/descompactado/202411_Servidores_SIAPE/202411_Remuneracao.csv", encoding='iso-8859-1', sep=";")

/tmp/ipykernel_11028/3046280270.py:1: DtypeWarning: Columns (2,5,7,9,34,36,37,38,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df_c = pd.read_csv("../../../dados/dados_siape_bruto/descompactado/202411_Servidores_SIAPE/202411_Cadastro.csv", encoding='iso-8859-1', sep=";")
/tmp/ipykernel_11028/3046280270.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_r = pd.read_csv("../../../dados/dados_siape_bruto/descompactado/202411_Servidores_SIAPE/202411_Remuneracao.csv", encoding='iso-8859-1', sep=";")

In [5]:
df = pd.merge(df_c, df_r, on=["Id_SERVIDOR_PORTAL"], how="left")

In [8]:
df[df['NOME_x'].str.lower().str.contains('fernando augusto sampaio')]

        Id_SERVIDOR_PORTAL                                     NOME_x           CPF_x MATRICULA                         DESCRICAO_CARGO CLASSE_CARGO  REFERENCIA_CARGO PADRAO_CARGO  NIVEL_CARGO SIGLA_FUNCAO  NIVEL_FUNCAO                           FUNCAO  CODIGO_ATIVIDADE     ATIVIDADE OPCAO_PARCIAL  COD_UORG_LOTACAO                          UORG_LOTACAO  COD_ORG_LOTACAO            ORG_LOTACAO  COD_ORGSUP_LOTACAO  ORGSUP_LOTACAO  COD_UORG_EXERCICIO                           UORG_EXERCICIO  COD_ORG_EXERCICIO          ORG_EXERCICIO  COD_ORGSUP_EXERCICIO ORGSUP_EXERCICIO  COD_TIPO_VINCULO TIPO_VINCULO  SITUACAO_VINCULO  DATA_INICIO_AFASTAMENTO  DATA_TERMINO_AFASTAMENTO        REGIME_JURIDICO JORNADA_DE_TRABALHO DATA_INGRESSO_CARGOFUNCAO  DATA_NOMEACAO_CARGOFUNCAO DATA_INGRESSO_ORGAO DOCUMENTO_INGRESSO_SERVICOPUBLICO DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO  DIPLOMA_INGRESSO_CARGOFUNCAO DIPLOMA_INGRESSO_ORGAO DIPLOMA_INGRESSO_SERVICOPUBLICO UF_EXERCICIO   ANO   MES           CPF_y                                     NOME_y  REMUNERAÇÃO BÁSICA BRUTA (R$) REMUNERAÇÃO BÁSICA BRUTA (U$) ABATE-TETO (R$) ABATE-TETO (U$) GRATIFICAÇÃO NATALINA (R$) GRATIFICAÇÃO NATALINA (U$) ABATE-TETO DA GRATIFICAÇÃO NATALINA (R$) ABATE-TETO DA GRATIFICAÇÃO NATALINA (U$) FÉRIAS (R$) FÉRIAS (U$) OUTRAS REMUNERAÇÕES EVENTUAIS (R$) OUTRAS REMUNERAÇÕES EVENTUAIS (U$) IRRF (R$) IRRF (U$) PSS/RPGS (R$) PSS/RPGS (U$) DEMAIS DEDUÇÕES (R$) DEMAIS DEDUÇÕES (U$) PENSÃO MILITAR (R$) PENSÃO MILITAR (U$) FUNDO DE SAÚDE (R$) FUNDO DE SAÚDE (U$) TAXA DE OCUPAÇÃO IMÓVEL FUNCIONAL (R$) TAXA DE OCUPAÇÃO IMÓVEL FUNCIONAL (U$) REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (R$) REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (U$) VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - CIVIL (R$)(*) VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - CIVIL (U$)(*) VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - MILITAR (R$)(*) VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - MILITAR (U$)(*) VERBAS INDENIZATÓRIAS PROGRAMA DESLIGAMENTO VOLUNTÁRIO  MP 792/2017 (R$) VERBAS INDENIZATÓRIAS PROGRAMA DESLIGAMENTO VOLUNTÁRIO  MP 792/2017 (U$) TOTAL DE VERBAS INDENIZATÓRIAS (R$)(*) TOTAL DE VERBAS INDENIZATÓRIAS (U$)(*)
238949             3332760  FERNANDO AUGUSTO SAMPAIO BONAFE FERNANDES  ***.409.137-**   010****  ANALISTA TRIBUTARIO REC FEDERAL BRASIL            S               0.0          002          0.0           -1          -1.0                   Sem informação                -1  Sem informaç           NaN    17600000001688  ALF/VCP/ALF RFB NO AER INT VIRACOPOS            17600  MINISTERIO DA FAZENDA                  -1  Sem informação      17600000001392  SRRF/8RF/SUPERINTENDENCIA REG RFB 8A RF              17600  MINISTERIO DA FAZENDA                    -1   Sem informação                 2        Cargo  ATIVO PERMANENTE                      NaN                       NaN  REGIME JURIDICO UNICO   40 HORAS SEMANAIS                30/12/2016                        NaN          19/06/2023                               719                           24/02/2014                           NaN                    LEI                        PORTARIA           -1  2024  11.0  ***.409.137-**  FERNANDO AUGUSTO SAMPAIO BONAFE FERNANDES                       20693.96                          0,00            0,00            0,00                   17693,96                       0,00                                     0,00                                     0,00        0,00        0,00                               0,00                               0,00  -7829,00      0,00      -1817,70          0,00             -9224,91                 0,00                0,00                0,00                0,00                0,00                                   0,00                                   0,00                                    19516,31                                        0,00                                                                  1139,66                                                                     0,00                                                                       0,00                                                                       0,00                                                                      0,00                                                                      0,00                                1139,66                                   0,00
238950             3332760  FERNANDO AUGUSTO SAMPAIO BONAFE FERNANDES  ***.409.137-**   010****                            Sem informaç          NaN              -1.0           -1         -1.0          FGR           1.0  FUNCAO GRATIFICADA LEI 8.216/91                56    ASSISTENTE           NaN    17600000001688  ALF/VCP/ALF RFB NO AER INT VIRACOPOS            17600  MINISTERIO DA FAZENDA                  -1  Sem informação      17600000001392  SRRF/8RF/SUPERINTENDENCIA REG RFB 8A RF              17600  MINISTERIO DA FAZENDA                    -1   Sem informação                 1       Função  ATIVO PERMANENTE                      NaN                       NaN  REGIME JURIDICO UNICO   40 HORAS SEMANAIS                16/09/2024                        NaN          19/06/2023                               719                           24/02/2014                           NaN                    LEI                        PORTARIA           SP  2024  11.0  ***.409.137-**  FERNANDO AUGUSTO SAMPAIO BONAFE FERNANDES                       20693.96                          0,00            0,00            0,00                   17693,96                       0,00                                     0,00                                     0,00        0,00        0,00                               0,00                               0,00  -7829,00      0,00      -1817,70          0,00             -9224,91                 0,00                0,00                0,00                0,00                0,00                                   0,00                                   0,00                                    19516,31                                        0,00                                                                  1139,66                                                                     0,00                                                                       0,00                                                                       0,00                                                                      0,00                                                                      0,00                                1139,66                                   0,00

In [6]:
# Converte a coluna removendo R$, espaços e trocando vírgula por ponto
df["REMUNERAÇÃO BÁSICA BRUTA (R$)"] = (
    df["REMUNERAÇÃO BÁSICA BRUTA (R$)"]
    .astype(str)
    .str.replace("R$", "", regex=False)
    .str.replace(".", "", regex=False)   # remove separador de milhar
    .str.replace(",", ".", regex=False)  # troca vírgula decimal por ponto
    .str.strip()
    .astype(float)
)

In [ ]:
df.groupby("DESCRICAO_CARGO")[["REMUNERAÇÃO BÁSICA BRUTA (R$)"]].sum().sort_values(
    by="REMUNERAÇÃO BÁSICA BRUTA (R$)", ascending=False
).style.format("R$ {:,.2f}".format)

In [32]:
import pandas as pd
from IPython.display import display, Markdown

# Mostrar título e explicação
display(Markdown("""
# 🧾 Portal da Transparência - Base SIAPE

## 🔍 Análise agrupada por **Descrição do Cargo**

Agrupamento dos dados com base no campo `DESCRICAO_CARGO`, ordenado pelo **Quantidade de servidores** decrescente.
"""))

# Agrupar
resumo = df.groupby("DESCRICAO_CARGO").agg({
    "REMUNERAÇÃO BÁSICA BRUTA (R$)": ["sum", "count", "mean"]
})
resumo.columns = ["Total remuneração cargo", "Quantidade de servidores", "Média da remuneração"]
resumo = resumo.sort_values(by="Quantidade de servidores", ascending=False)
resumo = resumo.reset_index()

# Adiciona ranking
resumo.insert(0, "Posição", range(1, len(resumo) + 1))

# Cargos a destacar
cargos_destacados = [
    "AUDITOR-FISCAL DA RECEITA FEDERAL BRASIL",
    "ANALISTA TRIBUTARIO REC FEDERAL BRASIL"
]

# Extrair os dados que você quer mostrar:
top_n = 15
linhas_destaque = resumo[resumo["DESCRICAO_CARGO"].isin(cargos_destacados)]
parte_inicial = resumo.iloc[:top_n]

# Criar linha de reticências
linha_reticencias = pd.DataFrame([["...", "...", "...", "...", "..."]], columns=resumo.columns)

# Concatenar tudo
resumo_final = pd.concat([
    parte_inicial,
    linha_reticencias,
    linhas_destaque
], ignore_index=True)

# Função para destacar os cargos desejados
def destacar_cargos_condicional(linha):
    if linha["DESCRICAO_CARGO"] in cargos_destacados:
        return ['background-color: #ffe599'] * len(linha)
    return [''] * len(linha)

# Formatar e exibir
display(resumo_final.style
    .format({
        "Total remuneração cargo": lambda x: x if x == "..." else "R$ {:,.2f}".format(x),
        "Quantidade de servidores": lambda x: x if x == "..." else "{:,}".format(x),
        "Média da remuneração": lambda x: x if x == "..." else "R$ {:,.2f}".format(x)
    })
    .apply(destacar_cargos_condicional, axis=1)
    .hide(axis="index")
)

# 🧾 Portal da Transparência - Base SIAPE

## 🔍 Análise agrupada por **Descrição do Cargo**

Agrupamento dos dados com base no campo `DESCRICAO_CARGO`, ordenado pelo **Quantidade de servidores** decrescente.

In [34]:
import psycopg2

# Conexão com o banco
con = psycopg2.connect(
    dbname="siape",
    user="bonafe",
    password="ovopreto",
    host="localhost",
    port="5432"
)

# Criar cursor e executar algo
cur = con.cursor()
cur.execute("SELECT version();")
print(cur.fetchone())

# Fechar conexão
cur.close()
con.close()

('PostgreSQL 14.17 (Ubuntu 14.17-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit',)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 763951 entries, 0 to 763950
Data columns (total 81 columns):
 #   Column                                                                      Non-Null Count   Dtype
---  ------                                                                      --------------   -----
 0   Id_SERVIDOR_PORTAL                                                          763951 non-null  int64
 1   NOME_x                                                                      763951 non-null  object
 2   CPF_x                                                                       727884 non-null  object
 3   MATRICULA                                                                   763951 non-null  object
 4   DESCRICAO_CARGO                                                             763951 non-null  object
 5   CLASSE_CARGO                                                                579289 non-null  object
 6   REFERENCIA_CARGO                                                            727884 non-null  float64
 7   PADRAO_CARGO                                                                448834 non-null  object
 8   NIVEL_CARGO                                                                 727884 non-null  float64
 9   SIGLA_FUNCAO                                                                763951 non-null  object
 10  NIVEL_FUNCAO                                                                763950 non-null  float64
 11  FUNCAO                                                                      763951 non-null  object
 12  CODIGO_ATIVIDADE                                                            763951 non-null  int64
 13  ATIVIDADE                                                                   763951 non-null  object
 14  OPCAO_PARCIAL                                                               59494 non-null   object
 15  COD_UORG_LOTACAO                                                            763951 non-null  int64
 16  UORG_LOTACAO                                                                763951 non-null  object
 17  COD_ORG_LOTACAO                                                             763951 non-null  int64
 18  ORG_LOTACAO                                                                 763951 non-null  object
 19  COD_ORGSUP_LOTACAO                                                          763951 non-null  int64
 20  ORGSUP_LOTACAO                                                              763951 non-null  object
 21  COD_UORG_EXERCICIO                                                          763951 non-null  int64
 22  UORG_EXERCICIO                                                              763951 non-null  object
 23  COD_ORG_EXERCICIO                                                           763951 non-null  int64
 24  ORG_EXERCICIO                                                               763951 non-null  object
 25  COD_ORGSUP_EXERCICIO                                                        763951 non-null  int64
 26  ORGSUP_EXERCICIO                                                            763951 non-null  object
 27  COD_TIPO_VINCULO                                                            763951 non-null  int64
 28  TIPO_VINCULO                                                                763951 non-null  object
 29  SITUACAO_VINCULO                                                            763951 non-null  object
 30  DATA_INICIO_AFASTAMENTO                                                     0 non-null       float64
 31  DATA_TERMINO_AFASTAMENTO                                                    0 non-null       float64
 32  REGIME_JURIDICO                                                             763951 non-null  object
 33  JORNADA_DE_TRABALHO                                                         763951 non-null  object
 34  DATA_INGRESSO_CARGOFUNCAO                                                   685479 non-null  object
 35  DATA_NOMEACAO_CARGOFUNCAO                                                   0 non-null       float64
 36  DATA_INGRESSO_ORGAO                                                         727827 non-null  object
 37  DOCUMENTO_INGRESSO_SERVICOPUBLICO                                           660127 non-null  object
 38  DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO                                        662662 non-null  object
 39  DIPLOMA_INGRESSO_CARGOFUNCAO                                                0 non-null       float64
 40  DIPLOMA_INGRESSO_ORGAO                                                      763951 non-null  object
 41  DIPLOMA_INGRESSO_SERVICOPUBLICO                                             763951 non-null  object
 42  UF_EXERCICIO                                                                763951 non-null  object
 43  ANO                                                                         620273 non-null  object
 44  MES                                                                         620273 non-null  float64
 45  CPF_y                                                                       620273 non-null  object
 46  NOME_y                                                                      620273 non-null  object
 47  REMUNERAÇÃO BÁSICA BRUTA (R$)                                               620273 non-null  float64
 48  REMUNERAÇÃO BÁSICA BRUTA (U$)                                               620273 non-null  object
 49  ABATE-TETO (R$)                                                             620273 non-null  object
 50  ABATE-TETO (U$)                                                             620273 non-null  object
 51  GRATIFICAÇÃO NATALINA (R$)                                                  620273 non-null  object
 52  GRATIFICAÇÃO NATALINA (U$)                                                  620273 non-null  object
 53  ABATE-TETO DA GRATIFICAÇÃO NATALINA (R$)                                    620273 non-null  object
 54  ABATE-TETO DA GRATIFICAÇÃO NATALINA (U$)                                    620273 non-null  object
 55  FÉRIAS (R$)                                                                 620273 non-null  object
 56  FÉRIAS (U$)                                                                 620273 non-null  object
 57  OUTRAS REMUNERAÇÕES EVENTUAIS (R$)                                          620273 non-null  object
 58  OUTRAS REMUNERAÇÕES EVENTUAIS (U$)                                          620273 non-null  object
 59  IRRF (R$)                                                                   620273 non-null  object
 60  IRRF (U$)                                                                   620273 non-null  object
 61  PSS/RPGS (R$)                                                               620273 non-null  object
 62  PSS/RPGS (U$)                                                               620273 non-null  object
 63  DEMAIS DEDUÇÕES (R$)                                                        620273 non-null  object
 64  DEMAIS DEDUÇÕES (U$)                                                        620273 non-null  object
 65  PENSÃO MILITAR (R$)                                                         620273 non-null  object
 66  PENSÃO MILITAR (U$)                                                         620273 non-null  object
 67  FUNDO DE SAÚDE (R$)                                                         620273 non-null  object
 68  FUNDO DE SAÚDE (U$)                                                         620273 non-null  object
 69  TAXA DE OCUPAÇÃO IMÓVEL FUNCIONAL (R$)                                      620273 non-null  object
 70  TAXA DE OCUPAÇÃO IMÓVEL FUNCIONAL (U$)                                      620273 non-null  object
 71  REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (R$)                                 620273 non-null  object
 72  REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (U$)                                 620273 non-null  object
 73  VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - CIVIL (R$)(*)    620273 non-null  object
 74  VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - CIVIL (U$)(*)    620273 non-null  object
 75  VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - MILITAR (R$)(*)  620273 non-null  object
 76  VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - MILITAR (U$)(*)  620273 non-null  object
 77  VERBAS INDENIZATÓRIAS PROGRAMA DESLIGAMENTO VOLUNTÁRIO  MP 792/2017 (R$)   620273 non-null  object
 78  VERBAS INDENIZATÓRIAS PROGRAMA DESLIGAMENTO VOLUNTÁRIO  MP 792/2017 (U$)   620273 non-null  object
 79  TOTAL DE VERBAS INDENIZATÓRIAS (R$)(*)                                      620273 non-null  object
 80  TOTAL DE VERBAS INDENIZATÓRIAS (U$)(*)                                      620273 non-null  object
dtypes: float64(9), int64(9), object(63)
memory usage: 477.9+ MB

In [36]:
import pandas as pd

# Lista de colunas que parecem ser valores monetários (mesmo sendo "object")
colunas_monetarias = [col for col in df.columns if "(R$)" in col or "REMUNERAÇÃO" in col or "VERBAS" in col or "(U$)" in col]

# Função para converter valores monetários, tratando vírgula e ponto
def para_float(valor):
    try:
        if isinstance(valor, str):
            valor = valor.replace('.', '').replace(',', '.')
        return float(valor)
    except:
        return None

# Aplicar conversão
for col in colunas_monetarias:
    df[col] = df[col].apply(para_float)

# Datas como string para datetime (opcional)
colunas_datas = [col for col in df.columns if "DATA_" in col]
for col in colunas_datas:
    df[col] = pd.to_datetime(df[col], errors='coerce')

# A coluna MES precisa ser int para join futuro
df["MES"] = df["MES"].fillna(0).astype(int)
df["ANO"] = df["ANO"].fillna(0).astype(int)

/tmp/ipykernel_11028/1343491748.py:22: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df[col] = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_11028/1343491748.py:22: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df[col] = pd.to_datetime(df[col], errors='coerce')
/tmp/ipykernel_11028/1343491748.py:22: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df[col] = pd.to_datetime(df[col], errors='coerce')

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 763951 entries, 0 to 763950
Data columns (total 81 columns):
 #   Column                                                                      Non-Null Count   Dtype
---  ------                                                                      --------------   -----
 0   Id_SERVIDOR_PORTAL                                                          763951 non-null  int64
 1   NOME_x                                                                      763951 non-null  object
 2   CPF_x                                                                       727884 non-null  object
 3   MATRICULA                                                                   763951 non-null  object
 4   DESCRICAO_CARGO                                                             763951 non-null  object
 5   CLASSE_CARGO                                                                579289 non-null  object
 6   REFERENCIA_CARGO                                                            727884 non-null  float64
 7   PADRAO_CARGO                                                                448834 non-null  object
 8   NIVEL_CARGO                                                                 727884 non-null  float64
 9   SIGLA_FUNCAO                                                                763951 non-null  object
 10  NIVEL_FUNCAO                                                                763950 non-null  float64
 11  FUNCAO                                                                      763951 non-null  object
 12  CODIGO_ATIVIDADE                                                            763951 non-null  int64
 13  ATIVIDADE                                                                   763951 non-null  object
 14  OPCAO_PARCIAL                                                               59494 non-null   object
 15  COD_UORG_LOTACAO                                                            763951 non-null  int64
 16  UORG_LOTACAO                                                                763951 non-null  object
 17  COD_ORG_LOTACAO                                                             763951 non-null  int64
 18  ORG_LOTACAO                                                                 763951 non-null  object
 19  COD_ORGSUP_LOTACAO                                                          763951 non-null  int64
 20  ORGSUP_LOTACAO                                                              763951 non-null  object
 21  COD_UORG_EXERCICIO                                                          763951 non-null  int64
 22  UORG_EXERCICIO                                                              763951 non-null  object
 23  COD_ORG_EXERCICIO                                                           763951 non-null  int64
 24  ORG_EXERCICIO                                                               763951 non-null  object
 25  COD_ORGSUP_EXERCICIO                                                        763951 non-null  int64
 26  ORGSUP_EXERCICIO                                                            763951 non-null  object
 27  COD_TIPO_VINCULO                                                            763951 non-null  int64
 28  TIPO_VINCULO                                                                763951 non-null  object
 29  SITUACAO_VINCULO                                                            763951 non-null  object
 30  DATA_INICIO_AFASTAMENTO                                                     0 non-null       datetime64[ns]
 31  DATA_TERMINO_AFASTAMENTO                                                    0 non-null       datetime64[ns]
 32  REGIME_JURIDICO                                                             763951 non-null  object
 33  JORNADA_DE_TRABALHO                                                         763951 non-null  object
 34  DATA_INGRESSO_CARGOFUNCAO                                                   685479 non-null  datetime64[ns]
 35  DATA_NOMEACAO_CARGOFUNCAO                                                   0 non-null       datetime64[ns]
 36  DATA_INGRESSO_ORGAO                                                         727827 non-null  datetime64[ns]
 37  DOCUMENTO_INGRESSO_SERVICOPUBLICO                                           660127 non-null  object
 38  DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO                                        662662 non-null  datetime64[ns]
 39  DIPLOMA_INGRESSO_CARGOFUNCAO                                                0 non-null       float64
 40  DIPLOMA_INGRESSO_ORGAO                                                      763951 non-null  object
 41  DIPLOMA_INGRESSO_SERVICOPUBLICO                                             763951 non-null  object
 42  UF_EXERCICIO                                                                763951 non-null  object
 43  ANO                                                                         763951 non-null  int64
 44  MES                                                                         763951 non-null  int64
 45  CPF_y                                                                       620273 non-null  object
 46  NOME_y                                                                      620273 non-null  object
 47  REMUNERAÇÃO BÁSICA BRUTA (R$)                                               620273 non-null  float64
 48  REMUNERAÇÃO BÁSICA BRUTA (U$)                                               620273 non-null  float64
 49  ABATE-TETO (R$)                                                             620273 non-null  float64
 50  ABATE-TETO (U$)                                                             620273 non-null  float64
 51  GRATIFICAÇÃO NATALINA (R$)                                                  620273 non-null  float64
 52  GRATIFICAÇÃO NATALINA (U$)                                                  620273 non-null  float64
 53  ABATE-TETO DA GRATIFICAÇÃO NATALINA (R$)                                    620273 non-null  float64
 54  ABATE-TETO DA GRATIFICAÇÃO NATALINA (U$)                                    620273 non-null  float64
 55  FÉRIAS (R$)                                                                 620273 non-null  float64
 56  FÉRIAS (U$)                                                                 620273 non-null  float64
 57  OUTRAS REMUNERAÇÕES EVENTUAIS (R$)                                          620273 non-null  float64
 58  OUTRAS REMUNERAÇÕES EVENTUAIS (U$)                                          620273 non-null  float64
 59  IRRF (R$)                                                                   620273 non-null  float64
 60  IRRF (U$)                                                                   620273 non-null  float64
 61  PSS/RPGS (R$)                                                               620273 non-null  float64
 62  PSS/RPGS (U$)                                                               620273 non-null  float64
 63  DEMAIS DEDUÇÕES (R$)                                                        620273 non-null  float64
 64  DEMAIS DEDUÇÕES (U$)                                                        620273 non-null  float64
 65  PENSÃO MILITAR (R$)                                                         620273 non-null  float64
 66  PENSÃO MILITAR (U$)                                                         620273 non-null  float64
 67  FUNDO DE SAÚDE (R$)                                                         620273 non-null  float64
 68  FUNDO DE SAÚDE (U$)                                                         620273 non-null  float64
 69  TAXA DE OCUPAÇÃO IMÓVEL FUNCIONAL (R$)                                      620273 non-null  float64
 70  TAXA DE OCUPAÇÃO IMÓVEL FUNCIONAL (U$)                                      620273 non-null  float64
 71  REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (R$)                                 620273 non-null  float64
 72  REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (U$)                                 620273 non-null  float64
 73  VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - CIVIL (R$)(*)    620273 non-null  float64
 74  VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - CIVIL (U$)(*)    620273 non-null  float64
 75  VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - MILITAR (R$)(*)  620273 non-null  float64
 76  VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - MILITAR (U$)(*)  620273 non-null  float64
 77  VERBAS INDENIZATÓRIAS PROGRAMA DESLIGAMENTO VOLUNTÁRIO  MP 792/2017 (R$)   620273 non-null  float64
 78  VERBAS INDENIZATÓRIAS PROGRAMA DESLIGAMENTO VOLUNTÁRIO  MP 792/2017 (U$)   620273 non-null  float64
 79  TOTAL DE VERBAS INDENIZATÓRIAS (R$)(*)                                      620273 non-null  float64
 80  TOTAL DE VERBAS INDENIZATÓRIAS (U$)(*)                                      620273 non-null  float64
dtypes: datetime64[ns](6), float64(38), int64(11), object(26)
memory usage: 477.9+ MB

In [39]:
import psycopg2

# SQL para criação da tabela
create_table_sql = """
CREATE TABLE siape (
    id SERIAL PRIMARY KEY,
    id_servidor_portal BIGINT,
    nome_x TEXT,
    cpf_x TEXT,
    matricula TEXT,
    descricao_cargo TEXT,
    classe_cargo TEXT,
    referencia_cargo NUMERIC,
    padrao_cargo TEXT,
    nivel_cargo NUMERIC,
    sigla_funcao TEXT,
    nivel_funcao NUMERIC,
    funcao TEXT,
    codigo_atividade INTEGER,
    atividade TEXT,
    opcao_parcial TEXT,
    cod_uorg_lotacao INTEGER,
    uorg_lotacao TEXT,
    cod_org_lotacao INTEGER,
    org_lotacao TEXT,
    cod_orgsup_lotacao INTEGER,
    orgsup_lotacao TEXT,
    cod_uorg_exercicio INTEGER,
    uorg_exercicio TEXT,
    cod_org_exercicio INTEGER,
    org_exercicio TEXT,
    cod_orgsup_exercicio INTEGER,
    orgsup_exercicio TEXT,
    cod_tipo_vinculo INTEGER,
    tipo_vinculo TEXT,
    situacao_vinculo TEXT,
    data_inicio_afastamento DATE,
    data_termino_afastamento DATE,
    regime_juridico TEXT,
    jornada_de_trabalho TEXT,
    data_ingresso_cargofuncao DATE,
    data_nomeacao_cargofuncao DATE,
    data_ingresso_orgao DATE,
    documento_ingresso_servicopublico TEXT,
    data_diploma_ingresso_servicopublico DATE,
    diploma_ingresso_cargofuncao TEXT,
    diploma_ingresso_orgao TEXT,
    diploma_ingresso_servicopublico TEXT,
    uf_exercicio TEXT,
    ano TEXT,
    mes INTEGER,
    cpf_y TEXT,
    nome_y TEXT,
    remuneracao_basica_bruta_rs NUMERIC,
    remuneracao_basica_bruta_us NUMERIC,
    abate_teto_rs NUMERIC,
    abate_teto_us NUMERIC,
    gratificacao_natalina_rs NUMERIC,
    gratificacao_natalina_us NUMERIC,
    abate_teto_grat_nat_rs NUMERIC,
    abate_teto_grat_nat_us NUMERIC,
    ferias_rs NUMERIC,
    ferias_us NUMERIC,
    outras_remuneracoes_eventuais_rs NUMERIC,
    outras_remuneracoes_eventuais_us NUMERIC,
    irrf_rs NUMERIC,
    irrf_us NUMERIC,
    pss_rpgs_rs NUMERIC,
    pss_rpgs_us NUMERIC,
    demais_deducoes_rs NUMERIC,
    demais_deducoes_us NUMERIC,
    pensao_militar_rs NUMERIC,
    pensao_militar_us NUMERIC,
    fundo_saude_rs NUMERIC,
    fundo_saude_us NUMERIC,
    taxa_ocupacao_imovel_funcional_rs NUMERIC,
    taxa_ocupacao_imovel_funcional_us NUMERIC,
    remuneracao_apos_deducoes_obrigatorias_rs NUMERIC,
    remuneracao_apos_deducoes_obrigatorias_us NUMERIC,
    verbas_indenizatorias_civil_rs NUMERIC,
    verbas_indenizatorias_civil_us NUMERIC,
    verbas_indenizatorias_militar_rs NUMERIC,
    verbas_indenizatorias_militar_us NUMERIC,
    verbas_indenizatorias_pdv_rs NUMERIC,
    verbas_indenizatorias_pdv_us NUMERIC,
    total_verbas_indenizatorias_rs NUMERIC,
    total_verbas_indenizatorias_us NUMERIC
);
"""

# Conectando ao banco e executando o SQL
try:
    con = psycopg2.connect(
        dbname="siape",
        user="bonafe",
        password="ovopreto",
        host="localhost",
        port="5432"
    )
    cur = con.cursor()
    cur.execute(create_table_sql)
    con.commit()
    print("✅ Tabela 'siape' criada com sucesso.")
except Exception as e:
    print("❌ Erro ao criar a tabela:", e)
finally:
    cur.close()
    con.close()

❌ Erro ao criar a tabela: relation "siape" already exists

In [ ]:
import os
import re
import pandas as pd
import unicodedata
import psycopg2
from psycopg2.extras import execute_values
from pathlib import Path
from tqdm import tqdm
from IPython.display import display, Markdown

# --------- 1. FUNÇÕES UTILITÁRIAS ---------

def limpar_coluna(col):
    col = col.strip().lower()
    col = unicodedata.normalize('NFKD', col).encode('ascii', 'ignore').decode('utf-8')

    col = col.replace("r$", "rs").replace("u$", "us")
    col = col.replace("(", "").replace(")", "").replace("*", "")
    col = re.sub(r'[^a-z0-9]+', '_', col)     # substitui qualquer sequência de não-letras/números por "_"
    col = re.sub(r'_+', '_', col)             # substitui múltiplos "_" por um só
    col = col.strip('_')                      # remove "_" do início e fim, se houver

    # ajuste específico para 'programa_desligamento_voluntario'
    col = col.replace('programa_desligamento_voluntario', 'pdv')
    col = col.replace('verbas_indenizatorias_registradas_em_sistemas_de_pessoal', 'verbas_indenizatorias')
    

    return col

def para_float(valor):
    try:
        if isinstance(valor, str):
            valor = valor.replace('.', '').replace(',', '.')
        return float(valor)
    except:
        return None

def gerar_create_table_sql(df, nome_tabela="siape"):
    tipo_sql = {
        "object": "TEXT",
        "int64": "BIGINT",
        "float64": "NUMERIC",
        "datetime64[ns]": "DATE",
        "bool": "BOOLEAN"
    }

    colunas_sql = []
    for coluna, tipo in df.dtypes.items():
        tipo_postgres = tipo_sql.get(str(tipo), "TEXT")
        colunas_sql.append(f'    {coluna} {tipo_postgres}')

    colunas_str = ",\n".join(colunas_sql)
    sql = f"""CREATE TABLE IF NOT EXISTS {nome_tabela} (
    id SERIAL PRIMARY KEY,
{colunas_str}
);"""
    return sql

def dados_ja_inseridos(ano, mes):
    try:
        con = psycopg2.connect(dbname="siape", user="bonafe", password="ovopreto", host="localhost", port="5432")
        cur = con.cursor()
        cur.execute("SELECT COUNT(*) FROM siape WHERE ano = %s AND mes = %s", (str(ano), mes))
        count = cur.fetchone()[0]
        cur.close()
        con.close()
        return count > 0
    except:
        return False

def inserir_siape_no_banco(df, ano, mes, chunk_size=5000):
    df.columns = [limpar_coluna(c) for c in df.columns]
    df["ano"] = str(ano)
    df["mes"] = int(mes)

    for col in [c for c in df.columns if "rs" in c or "us" in c or "remuneracao" in c or "verbas" in c]:
        df[col] = df[col].apply(para_float)
    for col in [c for c in df.columns if "data_" in c]:
        df[col] = pd.to_datetime(df[col], errors="coerce", dayfirst=True)
    if "id" in df.columns:
        df.drop(columns=["id"], inplace=True)

    colunas = list(df.columns)
    total = len(df)

    try:
        con = psycopg2.connect(dbname="siape", user="bonafe", password="ovopreto", host="localhost", port="5432")
        cur = con.cursor()
        for i in tqdm(range(0, total, chunk_size), desc=f"Inserindo {mes}/{ano}"):
            chunk = df.iloc[i:i+chunk_size]            
            valores = chunk.replace({pd.NaT: None}).where(pd.notnull(chunk), None).values.tolist()
            insert_query = f"INSERT INTO siape ({', '.join(colunas)}) VALUES %s"
            execute_values(cur, insert_query, valores)
        con.commit()
        display(Markdown(f"✅ **Inseridos {total} registros do mês {mes}/{ano}.**"))
    except Exception as e:
        display(Markdown(f"❌ **Erro ao inserir {mes}/{ano}:** {e}"))
    finally:
        cur.close()
        con.close()


# --------- 2. CRIA TABELA BASEADO EM UM MÊS DE EXEMPLO ---------

base_dir = Path("../../../dados/dados_siape_bruto/descompactado")
pastas = sorted(base_dir.glob("*_Servidores_SIAPE"))

if not pastas:
    raise Exception("Nenhuma pasta *_Servidores_SIAPE encontrada.")

pasta_exemplo = pastas[0]
ano_mes = pasta_exemplo.name.split("_")[0]
ano = int(ano_mes[:4])
mes = int(ano_mes[4:6])
cadastro_csv = pasta_exemplo / f"{ano_mes}_Cadastro.csv"
remuneracao_csv = pasta_exemplo / f"{ano_mes}_Remuneracao.csv"

df_c = pd.read_csv(cadastro_csv, encoding="iso-8859-1", sep=";", low_memory=False)
df_r = pd.read_csv(remuneracao_csv, encoding="iso-8859-1", sep=";", low_memory=False)
df = pd.merge(df_c, df_r, on="Id_SERVIDOR_PORTAL", how="left")

display (df.columns)

# 🧼 Corrige colunas ANTES de gerar SQL
df.columns = [limpar_coluna(c) for c in df.columns]



df["ano"] = int(ano)
df["mes"] = int(mes)


for col in [c for c in df.columns if "rs" in c or "us" in c or "remuneracao" in c or "verbas" in c]:
    df[col] = df[col].apply(para_float)
for col in [c for c in df.columns if "data_" in c]:
    df[col] = pd.to_datetime(df[col], errors="coerce", dayfirst=True)

display (df.columns)

# ✅ Agora sim, gerar o SQL com colunas já limpas
create_table_sql = gerar_create_table_sql(df)

# Cria ou recria a tabela no banco
try:
    con = psycopg2.connect(dbname="siape", user="bonafe", password="ovopreto", host="localhost", port="5432")
    cur = con.cursor()
    cur.execute("SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'siape');")
    existe = cur.fetchone()[0]

    if existe:
        resposta = input("A tabela 'siape' já existe. Deseja apagá-la e recriar? (s/n): ").strip().lower()
        if resposta == 's':
            cur.execute("DROP TABLE IF EXISTS siape CASCADE;")
            con.commit()
            print("🔁 Tabela antiga removida.")
        else:
            print("✅ Mantida a tabela existente. Nenhuma alteração.")

    cur.execute(create_table_sql)
    con.commit()
    cur.close()
    con.close()
    display(Markdown("✅ **Tabela `siape` verificada/criada com sucesso.**"))
except Exception as e:
    display(Markdown(f"❌ **Erro ao criar a tabela:** {e}"))


# --------- 3. INSERE OS DADOS DE TODOS OS MESES ---------

for pasta in pastas:
    try:
        ano_mes = pasta.name.split("_")[0]
        ano = int(ano_mes[:4])
        mes = int(ano_mes[4:6])

        display(Markdown(f"### 📂 Processando `{pasta.name}` ({mes}/{ano})"))

        if dados_ja_inseridos(ano, mes):
            display(Markdown("ℹ️ **Dados já inseridos anteriormente. Pulando.**"))
            continue

        cadastro_csv = pasta / f"{ano_mes}_Cadastro.csv"
        remuneracao_csv = pasta / f"{ano_mes}_Remuneracao.csv"

        if not cadastro_csv.exists() or not remuneracao_csv.exists():
            display(Markdown("⚠️ **Arquivos não encontrados. Pulando.**"))
            continue

        df_c = pd.read_csv(cadastro_csv, encoding="iso-8859-1", sep=";", low_memory=False)
        df_r = pd.read_csv(remuneracao_csv, encoding="iso-8859-1", sep=";", low_memory=False)
        df = pd.merge(df_c, df_r, on="Id_SERVIDOR_PORTAL", how="left")

        inserir_siape_no_banco(df, ano, mes)

    except Exception as e:
        display(Markdown(f"❌ **Erro ao processar `{pasta.name}`:** {e}"))

In [44]:
import psycopg2
from IPython.display import display, Markdown

# ---------- DROP + CREATE TABLE ----------
drop_create_sql = """
DROP TABLE IF EXISTS siape CASCADE;

CREATE TABLE siape (
    id SERIAL PRIMARY KEY,
    id_servidor_portal BIGINT,
    nome_x TEXT,
    cpf_x TEXT,
    matricula TEXT,
    descricao_cargo TEXT,
    classe_cargo TEXT,
    referencia_cargo NUMERIC,
    padrao_cargo TEXT,
    nivel_cargo NUMERIC,
    sigla_funcao TEXT,
    nivel_funcao NUMERIC,
    funcao TEXT,
    codigo_atividade INTEGER,
    atividade TEXT,
    opcao_parcial TEXT,
    cod_uorg_lotacao INTEGER,
    uorg_lotacao TEXT,
    cod_org_lotacao INTEGER,
    org_lotacao TEXT,
    cod_orgsup_lotacao INTEGER,
    orgsup_lotacao TEXT,
    cod_uorg_exercicio INTEGER,
    uorg_exercicio TEXT,
    cod_org_exercicio INTEGER,
    org_exercicio TEXT,
    cod_orgsup_exercicio INTEGER,
    orgsup_exercicio TEXT,
    cod_tipo_vinculo INTEGER,
    tipo_vinculo TEXT,
    situacao_vinculo TEXT,
    data_inicio_afastamento DATE,
    data_termino_afastamento DATE,
    regime_juridico TEXT,
    jornada_de_trabalho TEXT,
    data_ingresso_cargofuncao DATE,
    data_nomeacao_cargofuncao DATE,
    data_ingresso_orgao DATE,
    documento_ingresso_servicopublico TEXT,
    data_diploma_ingresso_servicopublico DATE,
    diploma_ingresso_cargofuncao TEXT,
    diploma_ingresso_orgao TEXT,
    diploma_ingresso_servicopublico TEXT,
    uf_exercicio TEXT,
    ano TEXT,
    mes INTEGER,
    cpf_y TEXT,
    nome_y TEXT,
    remuneracao_basica_bruta_rs NUMERIC,
    remuneracao_basica_bruta_us NUMERIC,
    abate_teto_rs NUMERIC,
    abate_teto_us NUMERIC,
    gratificacao_natalina_rs NUMERIC,
    gratificacao_natalina_us NUMERIC,
    abate_teto_grat_nat_rs NUMERIC,
    abate_teto_grat_nat_us NUMERIC,
    ferias_rs NUMERIC,
    ferias_us NUMERIC,
    outras_remuneracoes_eventuais_rs NUMERIC,
    outras_remuneracoes_eventuais_us NUMERIC,
    irrf_rs NUMERIC,
    irrf_us NUMERIC,
    pss_rpgs_rs NUMERIC,
    pss_rpgs_us NUMERIC,
    demais_deducoes_rs NUMERIC,
    demais_deducoes_us NUMERIC,
    pensao_militar_rs NUMERIC,
    pensao_militar_us NUMERIC,
    fundo_saude_rs NUMERIC,
    fundo_saude_us NUMERIC,
    taxa_ocupacao_imovel_funcional_rs NUMERIC,
    taxa_ocupacao_imovel_funcional_us NUMERIC,
    remuneracao_apos_deducoes_obrigatorias_rs NUMERIC,
    remuneracao_apos_deducoes_obrigatorias_us NUMERIC,
    verbas_indenizatorias_civil_rs NUMERIC,
    verbas_indenizatorias_civil_us NUMERIC,
    verbas_indenizatorias_militar_rs NUMERIC,
    verbas_indenizatorias_militar_us NUMERIC,
    verbas_indenizatorias_pdv_rs NUMERIC,
    verbas_indenizatorias_pdv_us NUMERIC,
    total_verbas_indenizatorias_rs NUMERIC,
    total_verbas_indenizatorias_us NUMERIC
);
"""

# ---------- Executa no banco ----------
try:
    con = psycopg2.connect(
        dbname="siape",
        user="bonafe",
        password="ovopreto",
        host="localhost",
        port="5432"
    )
    cur = con.cursor()
    cur.execute(drop_create_sql)
    con.commit()
    cur.close()
    con.close()
    display(Markdown("✅ **Tabela `siape` recriada com sucesso (DROP + CREATE).**"))
except Exception as e:
    display(Markdown(f"❌ **Erro ao criar a tabela:** {e}"))

✅ **Tabela `siape` recriada com sucesso (DROP + CREATE).**

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 728752 entries, 0 to 728751
Data columns (total 81 columns):
 #   Column                                                                 Non-Null Count   Dtype
---  ------                                                                 --------------   -----
 0   id_servidor_portal                                                     728752 non-null  int64
 1   nome_x                                                                 728752 non-null  object
 2   cpf_x                                                                  700438 non-null  object
 3   matricula                                                              728752 non-null  object
 4   descricao_cargo                                                        728752 non-null  object
 5   classe_cargo                                                           569134 non-null  object
 6   referencia_cargo                                                       700438 non-null  float64
 7   padrao_cargo                                                           503207 non-null  object
 8   nivel_cargo                                                            700438 non-null  float64
 9   sigla_funcao                                                           728752 non-null  object
 10  nivel_funcao                                                           728752 non-null  int64
 11  funcao                                                                 728752 non-null  object
 12  codigo_atividade                                                       728752 non-null  int64
 13  atividade                                                              728752 non-null  object
 14  opcao_parcial                                                          68874 non-null   object
 15  cod_uorg_lotacao                                                       728752 non-null  int64
 16  uorg_lotacao                                                           728752 non-null  object
 17  cod_org_lotacao                                                        728752 non-null  int64
 18  org_lotacao                                                            728752 non-null  object
 19  cod_orgsup_lotacao                                                     728752 non-null  int64
 20  orgsup_lotacao                                                         728752 non-null  object
 21  cod_uorg_exercicio                                                     728752 non-null  int64
 22  uorg_exercicio                                                         728752 non-null  object
 23  cod_org_exercicio                                                      728752 non-null  int64
 24  org_exercicio                                                          728752 non-null  object
 25  cod_orgsup_exercicio                                                   728752 non-null  int64
 26  orgsup_exercicio                                                       728752 non-null  object
 27  cod_tipo_vinculo                                                       728752 non-null  int64
 28  tipo_vinculo                                                           728752 non-null  object
 29  situacao_vinculo                                                       728752 non-null  object
 30  data_inicio_afastamento                                                35967 non-null   datetime64[ns]
 31  data_termino_afastamento                                               20602 non-null   datetime64[ns]
 32  regime_juridico                                                        728752 non-null  object
 33  jornada_de_trabalho                                                    728752 non-null  object
 34  data_ingresso_cargofuncao                                              667911 non-null  datetime64[ns]
 35  data_nomeacao_cargofuncao                                              0 non-null       datetime64[ns]
 36  data_ingresso_orgao                                                    700318 non-null  datetime64[ns]
 37  documento_ingresso_servicopublico                                      652308 non-null  object
 38  data_diploma_ingresso_servicopublico                                   659597 non-null  datetime64[ns]
 39  diploma_ingresso_cargofuncao                                           0 non-null       float64
 40  diploma_ingresso_orgao                                                 728752 non-null  object
 41  diploma_ingresso_servicopublico                                        728752 non-null  object
 42  uf_exercicio                                                           728752 non-null  int64
 43  ano                                                                    728752 non-null  object
 44  mes                                                                    728752 non-null  int64
 45  cpf_y                                                                  628962 non-null  object
 46  nome_y                                                                 628962 non-null  object
 47  remuneracao_basica_bruta_rs                                            628962 non-null  float64
 48  remuneracao_basica_bruta_us                                            628962 non-null  float64
 49  abateteto_rs                                                           628962 non-null  float64
 50  abateteto_us                                                           628962 non-null  float64
 51  gratificacao_natalina_rs                                               628962 non-null  float64
 52  gratificacao_natalina_us                                               628962 non-null  float64
 53  abateteto_da_gratificacao_natalina_rs                                  628962 non-null  float64
 54  abateteto_da_gratificacao_natalina_us                                  628962 non-null  float64
 55  ferias_rs                                                              628962 non-null  float64
 56  ferias_us                                                              628962 non-null  float64
 57  outras_remuneracoes_eventuais_rs                                       628962 non-null  float64
 58  outras_remuneracoes_eventuais_us                                       628962 non-null  float64
 59  irrf_rs                                                                628962 non-null  float64
 60  irrf_us                                                                628962 non-null  float64
 61  pssrpgs_rs                                                             628962 non-null  float64
 62  pssrpgs_us                                                             628962 non-null  float64
 63  demais_deducoes_rs                                                     628962 non-null  float64
 64  demais_deducoes_us                                                     628962 non-null  float64
 65  pensao_militar_rs                                                      628962 non-null  float64
 66  pensao_militar_us                                                      628962 non-null  float64
 67  fundo_de_saude_rs                                                      628962 non-null  float64
 68  fundo_de_saude_us                                                      628962 non-null  float64
 69  taxa_de_ocupacao_imovel_funcional_rs                                   628962 non-null  float64
 70  taxa_de_ocupacao_imovel_funcional_us                                   628962 non-null  float64
 71  remuneracao_apos_deducoes_obrigatorias_rs                              628962 non-null  float64
 72  remuneracao_apos_deducoes_obrigatorias_us                              628962 non-null  float64
 73  verbas_indenizatorias_registradas_em_sistemas_de_pessoal__civil_rs     628962 non-null  float64
 74  verbas_indenizatorias_registradas_em_sistemas_de_pessoal__civil_us     628962 non-null  float64
 75  verbas_indenizatorias_registradas_em_sistemas_de_pessoal__militar_rs   628962 non-null  float64
 76  verbas_indenizatorias_registradas_em_sistemas_de_pessoal__militar_us   628962 non-null  float64
 77  verbas_indenizatorias_programa_desligamento_voluntario__mp_7922017_rs  628962 non-null  float64
 78  verbas_indenizatorias_programa_desligamento_voluntario__mp_7922017_us  628962 non-null  float64
 79  total_de_verbas_indenizatorias_rs                                      628962 non-null  float64
 80  total_de_verbas_indenizatorias_us                                      628962 non-null  float64
dtypes: datetime64[ns](6), float64(37), int64(12), object(26)
memory usage: 455.9+ MB