In [4]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/anaclara/.local/lib/python3.10/site-packages (2.2.0)
Requirement already satisfied: tzdata>=2022.7 in /home/anaclara/.local/lib/python3.10/site-packages (from pandas) (2024.1)
Requirement already satisfied: numpy<2,>=1.22.4 in /home/anaclara/.local/lib/python3.10/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/anaclara/.local/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [5]:
import pandas as pd

/tmp/ipykernel_4117/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [9]:
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [66]:
df = pd.read_csv('../../dados/dados_siape_bruto/descompactado/202311_Servidores_SIAPE/202311_Cadastro.csv', encoding='iso-8859-1', sep=';')

/tmp/ipykernel_4117/2897270729.py:1: DtypeWarning: Columns (2,5,7,9,34,36,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../../dados/dados_siape_bruto/descompactado/202311_Servidores_SIAPE/202311_Cadastro.csv', encoding='iso-8859-1', sep=';')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748596 entries, 0 to 748595
Data columns (total 43 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Id_SERVIDOR_PORTAL                    748596 non-null  int64
 1   NOME                                  748596 non-null  object
 2   CPF                                   712000 non-null  object
 3   MATRICULA                             748596 non-null  object
 4   DESCRICAO_CARGO                       748596 non-null  object
 5   CLASSE_CARGO                          569395 non-null  object
 6   REFERENCIA_CARGO                      712000 non-null  float64
 7   PADRAO_CARGO                          441081 non-null  object
 8   NIVEL_CARGO                           712000 non-null  float64
 9   SIGLA_FUNCAO                          748596 non-null  object
 10  NIVEL_FUNCAO                          748596 non-null  int64
 11  FUNCAO                                748596 non-null  object
 12  CODIGO_ATIVIDADE                      748596 non-null  int64
 13  ATIVIDADE                             748596 non-null  object
 14  OPCAO_PARCIAL                         59519 non-null   object
 15  COD_UORG_LOTACAO                      748596 non-null  int64
 16  UORG_LOTACAO                          748596 non-null  object
 17  COD_ORG_LOTACAO                       748596 non-null  int64
 18  ORG_LOTACAO                           748596 non-null  object
 19  COD_ORGSUP_LOTACAO                    748596 non-null  int64
 20  ORGSUP_LOTACAO                        748596 non-null  object
 21  COD_UORG_EXERCICIO                    748596 non-null  int64
 22  UORG_EXERCICIO                        748596 non-null  object
 23  COD_ORG_EXERCICIO                     748596 non-null  int64
 24  ORG_EXERCICIO                         748596 non-null  object
 25  COD_ORGSUP_EXERCICIO                  748596 non-null  int64
 26  ORGSUP_EXERCICIO                      748596 non-null  object
 27  COD_TIPO_VINCULO                      748596 non-null  int64
 28  TIPO_VINCULO                          748596 non-null  object
 29  SITUACAO_VINCULO                      748596 non-null  object
 30  DATA_INICIO_AFASTAMENTO               0 non-null       float64
 31  DATA_TERMINO_AFASTAMENTO              0 non-null       float64
 32  REGIME_JURIDICO                       748596 non-null  object
 33  JORNADA_DE_TRABALHO                   748596 non-null  object
 34  DATA_INGRESSO_CARGOFUNCAO             670498 non-null  object
 35  DATA_NOMEACAO_CARGOFUNCAO             0 non-null       float64
 36  DATA_INGRESSO_ORGAO                   711947 non-null  object
 37  DOCUMENTO_INGRESSO_SERVICOPUBLICO     649248 non-null  object
 38  DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO  651996 non-null  object
 39  DIPLOMA_INGRESSO_CARGOFUNCAO          0 non-null       float64
 40  DIPLOMA_INGRESSO_ORGAO                748596 non-null  object
 41  DIPLOMA_INGRESSO_SERVICOPUBLICO       748596 non-null  object
 42  UF_EXERCICIO                          748596 non-null  int64
dtypes: float64(6), int64(11), object(26)
memory usage: 245.6+ MB

In [10]:
df.sample(5)

,Id_SERVIDOR_PORTAL,NOME,CPF,MATRICULA,DESCRICAO_CARGO,CLASSE_CARGO,REFERENCIA_CARGO,PADRAO_CARGO,NIVEL_CARGO,SIGLA_FUNCAO,NIVEL_FUNCAO,FUNCAO,CODIGO_ATIVIDADE,ATIVIDADE,OPCAO_PARCIAL,COD_UORG_LOTACAO,UORG_LOTACAO,COD_ORG_LOTACAO,ORG_LOTACAO,COD_ORGSUP_LOTACAO,ORGSUP_LOTACAO,COD_UORG_EXERCICIO,UORG_EXERCICIO,COD_ORG_EXERCICIO,ORG_EXERCICIO,COD_ORGSUP_EXERCICIO,ORGSUP_EXERCICIO,COD_TIPO_VINCULO,TIPO_VINCULO,SITUACAO_VINCULO,DATA_INICIO_AFASTAMENTO,DATA_TERMINO_AFASTAMENTO,REGIME_JURIDICO,JORNADA_DE_TRABALHO,DATA_INGRESSO_CARGOFUNCAO,DATA_NOMEACAO_CARGOFUNCAO,DATA_INGRESSO_ORGAO,DOCUMENTO_INGRESSO_SERVICOPUBLICO,DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO,DIPLOMA_INGRESSO_CARGOFUNCAO,DIPLOMA_INGRESSO_ORGAO,DIPLOMA_INGRESSO_SERVICOPUBLICO,UF_EXERCICIO
369622,310630679,JULIANO DA SILVA REIS,***.535.100-**,023****,Sem informa√ß,NaN,-1.0,-1,-1.0,GF,27,FUNCAO GRATIFICADA,281,CHEFE DE UNIDADE,S,26443024000000,HOSPITAL UNIVERSITARIO DA UFSM,26443,Empresa Brasileira de Servi√ßos Hospitalares,15000,Minist√©rio da Educa√ß√£o,-3,Inv√°lido,26443,Empresa Brasileira de Servi√ßos Hospitalares,15000,Minist√©rio da Educa√ß√£o,1,Fun√ß√£o,CELETISTA/EMPREGADO,NaN,NaN,CONSOLIDACAO DAS LEIS DO TRABALHO,40 HORAS SEMANAIS,08/03/2022,NaN,01/12/2016,000000000,01/12/2016,NaN,CONTRATO,CONTRATO,-1
183416,312636400,EDSON LIMA DA PURIFICACAO,***.231.877-**,012****,ANALISTA TRIBUTARIO REC FEDERAL BRASIL,S,0.0,003,0.0,-1,-1,Sem informa√ß√£o,-1,Sem informa√ß,NaN,17600000000671,DEMAC/RJ/DEL ESP RFB MAIORES CONTRIBUINT,17600,MINISTERIO DA FAZENDA,20101,Presid√™ncia da Rep√∫blica,17600000000689,EQUIPE GESTAO CRED TRIB E DIR CRED 5,17600,MINISTERIO DA FAZENDA,20101,Presid√™ncia da Rep√∫blica,2,Cargo,ATIVO PERMANENTE,NaN,NaN,REGIME JURIDICO UNICO,40 HORAS SEMANAIS,30/12/2016,NaN,19/06/2023,000000007,30/01/1998,NaN,LEI,PORTARIA,-1
572641,310613276,RAFAELLA FERNANDA VILLA NOVA DA SILVA,***.111.424-**,028****,ASSISTENTE DE ALUNO,C,0.0,406,0.0,-1,-1,Sem informa√ß√£o,-1,Sem informa√ß,NaN,26418000000033,DIRECAO GERAL/CAMPUS BARREIROS,26418,Instituto Federal de Pernambuco,15000,Minist√©rio da Educa√ß√£o,26418000000088,COORD GERAL DE ASSIST AO ESTUDANTE/C BAR,26418,Instituto Federal de Pernambuco,15000,Minist√©rio da Educa√ß√£o,2,Cargo,ATIVO PERMANENTE,NaN,NaN,REGIME JURIDICO UNICO,40 HORAS SEMANAIS,12/11/2015,NaN,15/02/2022,2551,12/11/2015,NaN,PORTARIA,PORTARIA,-1
93152,310486271,BRUNO BELLAN HERINGER,***.568.827-**,023****,ASSISTENTE EM ADMINISTRACAO,D,0.0,305,0.0,-1,-1,Sem informa√ß√£o,-1,Sem informa√ß,NaN,26406000001176,CAMPUS VITORIA,26406,Instituto Federal do Esp√≠rito Santo,15000,Minist√©rio da Educa√ß√£o,26406000001193,COORD DE LICITACOES E COMPRAS,26406,Instituto Federal do Esp√≠rito Santo,15000,Minist√©rio da Educa√ß√£o,2,Cargo,ATIVO PERMANENTE,NaN,NaN,REGIME JURIDICO UNICO,40 HORAS SEMANAIS,12/05/2016,NaN,12/05/2016,NaN,12/05/2016,NaN,PORTARIA,CARTA,-1
141470,313097958,CRISTIANO CARDOSO DA SILVA,***.755.701-**,010****,TECNICO ADMINISTRATIVO,B,0.0,IV,0.0,-1,-1,Sem informa√ß√£o,-1,Sem informa√ß,NaN,40701000001209,"DIRETORIA DE PLANEJ, ADM. E LOGISTICA",40701,Instituto Brasileiro do Meio Ambiente e Recurs...,40211,MINISTERIO DO MEIO AMBIENTE,40701000001239,SERV. DE BENEF. APOSENTADORIAS E PENSOES,40701,Instituto Brasileiro do Meio Ambiente e Recurs...,40211,MINISTERIO DO MEIO AMBIENTE,2,Cargo,ATIVO PERMANENTE,NaN,NaN,REGIME JURIDICO UNICO,40 HORAS SEMANAIS,12/05/2014,NaN,25/04/2014,471_IBAMA,12/05/2014,NaN,PORTARIA,PORTARIA,-1

In [21]:
df_agrupado = df.groupby('REGIME_JURIDICO').size().reset_index(name='Quantidade')

In [25]:
display(df_agrupado) 
display(df_agrupado.info())

                        REGIME_JURIDICO  Quantidade
0     CONSOLIDACAO DAS LEIS DO TRABALHO       94520
1                   CONTRATO TEMPORARIO       32044
2                               ESTAGIO       16821
3                       ESTAGIO EMPRESA          78
4         MEDICO - PROGRAMA MAIS MEDICO       15988
5                      MEDICO RESIDENTE       10331
6                     NATUREZA ESPECIAL         736
7                 REGIME JURIDICO UNICO      536933
8                        REGIME MILITAR         217
9   RESIDENCIA MEDICA COMUNIDADE E FAMI           1
10         RESIDENCIA MULTIPROFISSIONAL        4331
11                         Sem informa√ß       36596

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REGIME_JURIDICO  12 non-null     object
 1   Quantidade       12 non-null     int64
dtypes: int64(1), object(1)
memory usage: 320.0+ bytes

None

In [68]:
df.value_counts('REGIME_JURIDICO')

REGIME_JURIDICO
REGIME JURIDICO UNICO                  536933
CONSOLIDACAO DAS LEIS DO TRABALHO       94520
Sem informa√ß                            36596
CONTRATO TEMPORARIO                     32044
ESTAGIO                                 16821
MEDICO - PROGRAMA MAIS MEDICO           15988
MEDICO RESIDENTE                        10331
RESIDENCIA MULTIPROFISSIONAL             4331
NATUREZA ESPECIAL                         736
REGIME MILITAR                            217
ESTAGIO EMPRESA                            78
RESIDENCIA MEDICA COMUNIDADE E FAMI         1
Name: count, dtype: int64

In [72]:
df_filtro = df[df['REGIME_JURIDICO'].str.contains('estagio empresa', case=False)]

In [73]:
display(df_filtro)

,Id_SERVIDOR_PORTAL,NOME,CPF,MATRICULA,DESCRICAO_CARGO,CLASSE_CARGO,REFERENCIA_CARGO,PADRAO_CARGO,NIVEL_CARGO,SIGLA_FUNCAO,NIVEL_FUNCAO,FUNCAO,CODIGO_ATIVIDADE,ATIVIDADE,OPCAO_PARCIAL,COD_UORG_LOTACAO,UORG_LOTACAO,COD_ORG_LOTACAO,ORG_LOTACAO,COD_ORGSUP_LOTACAO,ORGSUP_LOTACAO,COD_UORG_EXERCICIO,UORG_EXERCICIO,COD_ORG_EXERCICIO,ORG_EXERCICIO,COD_ORGSUP_EXERCICIO,ORGSUP_EXERCICIO,COD_TIPO_VINCULO,TIPO_VINCULO,SITUACAO_VINCULO,DATA_INICIO_AFASTAMENTO,DATA_TERMINO_AFASTAMENTO,REGIME_JURIDICO,JORNADA_DE_TRABALHO,DATA_INGRESSO_CARGOFUNCAO,DATA_NOMEACAO_CARGOFUNCAO,DATA_INGRESSO_ORGAO,DOCUMENTO_INGRESSO_SERVICOPUBLICO,DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO,DIPLOMA_INGRESSO_CARGOFUNCAO,DIPLOMA_INGRESSO_ORGAO,DIPLOMA_INGRESSO_SERVICOPUBLICO,UF_EXERCICIO
504,313727419,ABNER VIEIRA PEREIRA,***.490.347-**,033****,Sem informa√ß,NaN,-1.0,-1,-1.0,ETE,1,ESTAGIO EMPRESA,2473,ESTAGIARIO,NaN,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,1,Fun√ß√£o,ESTAGIARIO EMPRESA,NaN,NaN,ESTAGIO EMPRESA,30 HORAS SEMANAIS,01/11/2023,NaN,01/11/2023,NaN,NaN,NaN,CONTRATO,Inv√°lido,-1
35662,312003913,AMANDA NUNES LIMA,***.863.907-**,033****,Sem informa√ß,NaN,-1.0,-1,-1.0,ETE,1,ESTAGIO EMPRESA,2473,ESTAGIARIO,NaN,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,1,Fun√ß√£o,ESTAGIARIO EMPRESA,NaN,NaN,ESTAGIO EMPRESA,30 HORAS SEMANAIS,24/07/2023,NaN,24/07/2023,NaN,NaN,NaN,CONTRATO,Inv√°lido,-1
40473,311831443,ANA CLAUDIA FERREIRA LONGO MORAES,***.616.557-**,033****,Sem informa√ß,NaN,-1.0,-1,-1.0,ETE,1,ESTAGIO EMPRESA,2473,ESTAGIARIO,NaN,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,1,Fun√ß√£o,ESTAGIARIO EMPRESA,NaN,NaN,ESTAGIO EMPRESA,30 HORAS SEMANAIS,24/07/2023,NaN,24/07/2023,NaN,NaN,NaN,CONTRATO,Inv√°lido,-1
45091,309921682,ANA LUIZA RODRIGUES DE SOUSA,***.114.231-**,010****,Inv√°lido,NaN,0.0,NaN,0.0,-1,-1,Sem informa√ß√£o,-1,Sem informa√ß,NaN,-3,Inv√°lido,22202,Empresa Brasileira de Pesquisa Agropecu√°ria,13000,"Minist√©rio da Agricultura, Pecu√°ria e Abasteci...",22202001380080,DEPARTAMENTO DE GESTAO DE PESSOAS - DGP,22202,Empresa Brasileira de Pesquisa Agropecu√°ria,13000,"Minist√©rio da Agricultura, Pecu√°ria e Abasteci...",3,Outros,ESTAGIARIO EMPRESA,NaN,NaN,ESTAGIO EMPRESA,20 HORAS SEMANAIS,NaN,NaN,30/07/2014,NaN,NaN,NaN,LEI,Inv√°lido,-1
45227,311764784,ANA MARCIA INACIO CANDIDO,***.271.337-**,032****,Sem informa√ß,NaN,-1.0,-1,-1.0,ETE,1,ESTAGIO EMPRESA,2473,ESTAGIARIO,NaN,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,1,Fun√ß√£o,ESTAGIARIO EMPRESA,NaN,NaN,ESTAGIO EMPRESA,30 HORAS SEMANAIS,12/01/2022,NaN,12/01/2022,NaN,NaN,NaN,CONTRATO,Inv√°lido,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692323,311869259,VINICIUS RAMOS DA SILVA,***.435.357-**,033****,Sem informa√ß,NaN,-1.0,-1,-1.0,ETE,1,ESTAGIO EMPRESA,2473,ESTAGIARIO,NaN,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,1,Fun√ß√£o,ESTAGIARIO EMPRESA,NaN,NaN,ESTAGIO EMPRESA,30 HORAS SEMANAIS,09/09/2022,NaN,09/09/2022,NaN,NaN,NaN,CONTRATO,Inv√°lido,-1
693732,313114388,VITOR FERREIRA DA SILVA,***.210.997-**,033****,Sem informa√ß,NaN,-1.0,-1,-1.0,ETE,1,ESTAGIO EMPRESA,2473,ESTAGIARIO,NaN,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,1,Fun√ß√£o,ESTAGIARIO EMPRESA,NaN,NaN,ESTAGIO EMPRESA,30 HORAS SEMANAIS,25/10/2022,NaN,25/10/2022,NaN,NaN,NaN,CONTRATO,Inv√°lido,-1
705783,312143944,WILLIAM DIAS DUARTE,***.277.517-**,033****,Sem informa√ß,NaN,-1.0,-1,-1.0,ETE,1,ESTAGIO EMPRESA,2473,ESTAGIARIO,NaN,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,1,Fun√ß√£o,ESTAGIARIO EMPRESA,NaN,NaN,ESTAGIO EMPRESA,30 HORAS SEMANAIS,13/04/2023,NaN,13/04/2023,NaN,NaN,NaN,CONTRATO,Inv√°lido,-1
708602,312095785,YAGO DE ARAUJO HENRIQUE,***.680.087-**,033****,Sem informa√ß,NaN,-1.0,-1,-1.0,ETE,2,ESTAGIO EMPRESA,2473,ESTAGIARIO,NaN,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,1,Fun√ß√£o,ESTAGIARIO EMPRESA,NaN,NaN,ESTAGIO EMPRESA,30 HORAS SEMANAIS,14/09/2023,NaN,14/09/2023,NaN,NaN,NaN,CONTRATO,Inv√°lido,-1
709276,313172084,YASMIN BARROS DE AMORIM,***.665.751-**,033****,Sem informa√ß,NaN,-1.0,-1,-1.0,ETE,1,ESTAGIO EMPRESA,2473,ESTAGIARIO,NaN,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,-3,Inv√°lido,20302,Nuclebr√°s Equipamentos Pesados,32000,Minist√©rio de Minas e Energia,1,Fun√ß√£o,ESTAGIARIO EMPRESA,NaN,NaN,ESTAGIO EMPRESA,30 HORAS SEMANAIS,19/01/2023,NaN,19/01/2023,NaN,NaN,NaN,CONTRATO,Inv√°lido,-1

In [17]:
v = 'oi'
display(type(df.groupby('REGIME_JURIDICO').size().reset_index()))

pandas.core.frame.DataFrame

In [ ]:
df[]

In [31]:
lista = [1, 2, 3, 'abelha', 'mel', 1.2]

for item in lista:
    display (f'{item}: {type(item)}')

"1: <class 'int'>"

"2: <class 'int'>"

"3: <class 'int'>"

"abelha: <class 'str'>"

"mel: <class 'str'>"

"1.2: <class 'float'>"

In [33]:
lista[3]

'abelha'

In [74]:
import pandas as pd

# Dados
dados = {
    'Pa√≠s': ['Brasil', 'Argentina', 'Estados Unidos', 'China', '√çndia'],
    'Continente': ['Am√©rica do Sul', 'Am√©rica do Sul', 'Am√©rica do Norte', '√Åsia', '√Åsia'],
    'Popula√ß√£o (milh√µes)': [211, 45, 331, 1441, 1380]
}

# Criar DataFrame
df = pd.DataFrame(dados)

# Exibir DataFrame
display(df)

             Pa√≠s        Continente  Popula√ß√£o (milh√µes)
0          Brasil    Am√©rica do Sul                  211
1       Argentina    Am√©rica do Sul                   45
2  Estados Unidos  Am√©rica do Norte                  331
3           China              √Åsia                 1441
4           √çndia              √Åsia                 1380

In [76]:
df['nova coluna'] = 'abelha'

display(df)

             Pa√≠s        Continente  Popula√ß√£o (milh√µes) nova coluna
0          Brasil    Am√©rica do Sul                  211      abelha
1       Argentina    Am√©rica do Sul                   45      abelha
2  Estados Unidos  Am√©rica do Norte                  331      abelha
3           China              √Åsia                 1441      abelha
4           √çndia              √Åsia                 1380      abelha

In [44]:
display (type(df['Pa√≠s']))
display (type(df[['Pa√≠s']]))
display (type(df[['Pa√≠s', 'Popula√ß√£o (milh√µes)']]))

pandas.core.series.Series

pandas.core.frame.DataFrame

pandas.core.frame.DataFrame

In [45]:
df[[True, False, False, False, True]]

     Pa√≠s      Continente  Popula√ß√£o (milh√µes)
0  Brasil  Am√©rica do Sul                  211
4   √çndia            √Åsia                 1380

# Passando os √≠ndices diretamente na fun√ß√£o VERSUS passando por uma vari√°vel
## s√£o equivalentes

vai depende ser vai usar a var√≠avel em outros lugares

In [53]:
series_contem_bra = df['Pa√≠s'].str.contains('Bra')
df[series_contem_bra

     Pa√≠s      Continente  Popula√ß√£o (milh√µes)
0  Brasil  Am√©rica do Sul                  211

## mais comum dessa forma abaixo

In [52]:
df[df['Pa√≠s'].str.contains('Bra')]

     Pa√≠s      Continente  Popula√ß√£o (milh√µes)
0  Brasil  Am√©rica do Sul                  211

In [60]:
df['Pa√≠s'].str.contains('r')

0     True
1     True
2    False
3    False
4    False
Name: Pa√≠s, dtype: bool

In [61]:
df['Popula√ß√£o (milh√µes)'] > 200

0     True
1    False
2     True
3     True
4     True
Name: Popula√ß√£o (milh√µes), dtype: bool

In [67]:
df['Pa√≠s'].str.contains('r') & (df['Popula√ß√£o (milh√µes)'] > 200)

KeyError: 'Pa√≠s'